### ISSUE TITLE
Problem z instalacją pillow

### ISSUE THREAD

**Issue by ADDJAR** [dekoza/kurs_django#3]
Witam
na to wygląda że stałem się wiernym "oglądaczem" Pana kursów, chociaż muszę się przyznać że nie mam jeszcze pojęcia do czego przyda mi akurat się Django?
Pojawił się u mnie pewien problem z instalacją pakietu pillow:
https://www.dropbox.com/s/dmjsrxfk2283yod/error_log.txt?dl=0
pracuje na Linux Mint 17 'Qiana'  KDE 64 bit - (a właściwie też cały czas się go ucze)
nie wiem jak poradzić sobie z tym problemem :/

**Comment by dekoza** [comment]
Proszę najpierw spróbować tej porady: [Using Pillow with Python 3 @ StackOverflow](http://stackoverflow.com/questions/23970006/using-pillow-with-python-3)

Odpowiadając natomiast na pierwszą część pytania: Django przydaje się w tych miejscach, gdzie potrzebujemy przechowywać coś w bazie i potem obrabiać i prezentować te dane w wygodny sposób ;)

**Comment by ADDJAR** [comment]
no to kolejne lamerskie pythanie: 
zastosować się do podanych instrukcji tzn. instalacji tych pakietów w stworzonym przeze mnie środowisku wirtualnym, czy lepiej zainstlować pakiety w "głownym' katalogu z pythonem ?

**Comment by ADDJAR** [comment]
to już może żeby nie spamić, zastosowałem się do podanych instrukcji
a w wirtualnym środowisku wykonałem polecenia:
$  pip3 install Pillow
Successfully installed Pillow
Cleaning up...
$ pip3 freeze > requirements.txt
$ cat requirements.txt
Django==1.7.1
Pillow==2.6.1
django-configurations==0.8

I działa, tada !!
Dziękuje ślicznie

**Comment by dekoza** [comment]
Bardzo się cieszę :) Pozdrawiam.
