### ISSUE TITLE
spotkanie 2

### ISSUE THREAD

**Issue by ADDJAR** [dekoza/kurs_django#4]
Witam
Pytanie nr 1
chodzi mi o samą konfigurację oraz gałęzie rozwojowe dodane za pomocą wtyczki git flow:
[feature/]  feat/
po wydaniu komendy:
$ git branch
dev,  fix/1, master
widzę tylko trzy gałęzie, a pozostałe? Nie dokońca jest to dla mnie zrozumiałe

Pytanie nr 2
Przypuśćmy taką sytuacje:
tworzę publiczne repo, jedna osoba z uczestników projektu dokonała zmian w kodzie i chce je "wypchnąć" do repozytorium - przy każdym wydaniu komendy:
$ git push 
woła o ligin i hasło do github lub bitbucket na moje konto, po co ? jak dokonać rozróżnienia na admina i zwykłych uczestników 

Pytanie nr 3
chodzi o samą komende:
$git push --set-upstream orgin
być może mi to umkneło, nie dokońca wiem czym różni się od samej komendy 
$git push

**Comment by dekoza** [comment]
1. Wtyczka git flow oferuje dodatkowe polecenia, które wspomagają uporządkowany rozwój projketu. Faktycznie za mało czasu poświęciłem temu poleceniu, za co przepraszam. Polecenie `git flow init` powoduje stworzenie konfiguracji dla tego polecenia, czyli np. wybranie przedrostków dla określonych **rodzajów** gałęzi ('feat/', 'fix/' itd.). Tworzenie gałęzi danego typu odbywa się poprzez wydanie odpowiednich poleceń, np. `git flow feature 'nazwa'` utworzy nam gałąź 'feat/nazwa' (przy pokazanej na filmie konfiguracji). Tak więc git flow wspomaga zarządzanie projektem poprzez łatwe tworzenie gałęzi przeznaczonych na określony rodzaj pracy.
2. Jeśli wszyscy uczestnicy projektu pracuję na tym samym zewnętrznym repozytorium i mają mieć możliwość wypychania zmian, to każdy z nich powinien otrzymać do tego repo prawo zapisu. W praktyce nie robi się czegoś takiego. Prawo zapisu do głównego repo powinni posiadać wyłącznie główni adminstratorzy/liderzy grup (czasem włącza się tutaj także testerów). Każdy programista powinien zrobić sobie fork głównego repozytorium, pracować wyłącznie na tym forku, a do głównego repo wysyłać tzw. pull request. Pokazywałem to podczas spotkania. Dodatkowym usprawnieniem w konfiguracji githuba jest wgranie kluczy SSH. Całość procedury jest opisana w ustawieniach repozytorium.
3. Pierwszą wystarczy wykonać raz - wypycha ona zmiany do repo `origin` (domyślnie jest to repozytorium, które sklonowaliśmy używając polecenia `git clone`) jednocześnie ustawiając to repozytorium jako domyślne zewnętrzne repo dla bieżącej gałęzi. Chodzi o to, że różne gałęzie mogą mieć różne zewnętrzne repozytoria (np. testy i produkcja) ustawione jako podstawowe do wypychania zmian..

**Comment by ADDJAR** [comment]
Ad.1,2
stworzyłem taką gałąź:
$ git branch 
  dev
* feat/fork_addjar
  master
dokonałem na niej zmian i wypchnołem do repo:
$ git push 
"warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': ADDJAR
Password for 'https://ADDJAR@github.com': 
Everything up-to-date"

Niestety nie widzę żadnych zmian na github, mam tylko trzy gałęzie
"przeskoczyłem" na gałąź dev, dokonałem zmian i wypchnołem do repo:
$ git push 
"warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': ADDJAR
Password for 'https://ADDJAR@github.com': 
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 333 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To https://github.com/ADDJAR/kurs_django.git
   de1ec62..8ba6e55  dev -> dev
"
zmiany na github są widoczne, o co kaman?

**Comment by dekoza** [comment]
Czy przed `git push` było zrobione `git commit` na tej konkretnej gałęzi? Bo w pierwszym przypadku komunikat jest taki, że nic nowego się nie pojawiło (Everything up to date), więc nie było potrzeby wypchnięcia.

**Comment by ADDJAR** [comment]
ano w zasadzie mogłem zrobić jakiegoś babola, no nic pierwszy odcinek kursu praktycznie streściłem (wolno idzie ale mam mało na to czasu), 
pouzupełniałem wiadomości na temat gita - to co udało mi się na jego temat znleźć jeszcze w sieci
dla osób które chciałyby skorzystać
https://bitbucket.org/addjar/ci-ga/overview
Dojdę do tego momentu i pewnie samo wyjdzie w praniu
