### ISSUE TITLE
Przestrzenie nazw, końcówka sp. 3

### ISSUE THREAD

**Issue by ADDJAR** [dekoza/kurs_django#6]
Witam
mam takie pytanko, przy końcówce spotkania trzeciego mówił Pan o przestrzeniach nazw i tak:
url(r'^shelf/',  include('shelf.urls', <b>name</b>='shelf')),
w funkcji include() jako parametr został przekazany atrybut <b>name</b>, nie powinno być?:
url(r'^shelf/',  include('shelf.urls', <b>namespace</b>='shelf')),

**Comment by dekoza** [comment]
Zgadza się, powinno być `namespace`. O ile pamiętam, to poprawiłem się na początku kolejnego odcinka.

**Comment by ADDJAR** [comment]
ok, dzięki tak też się domyśliłem, spojrzałem później na Pana repo :) 
troszkę będzie wolnego to przyśpieszę z kursami, do czwartego kursu jeszcze nie dotarłem
