### ISSUE TITLE
'NoneType' object is not callable sp.4  0:28:17

### ISSUE THREAD

**Issue by ADDJAR** [dekoza/kurs_django#7]
Przy próbie odpalenia aplikacji dostałem taki oto komunikat:
TypeError at /contact/

'NoneType' object is not callable

Request Method:     GET
Request URL:    http://127.0.0.1:8000/contact/
Django Version:     1.7.1
Exception Type:     TypeError
Exception Value:    

'NoneType' object is not callable

Exception Location:     /home/addjar/.virtualenvs/djangoENV/lib/python3.4/site-packages/django/views/generic/edit.py in get_form, line 45
Python Executable:  /home/addjar/.virtualenvs/djangoENV/bin/python
Python Version:     3.4.0
Python Path:    

['/home/addjar/Programowanie/django/kurs_django',
 '/home/addjar/.virtualenvs/djangoENV/lib/python3.4',
 '/home/addjar/.virtualenvs/djangoENV/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/addjar/.virtualenvs/djangoENV/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/addjar/.virtualenvs/djangoENV/lib/python3.4/site-packages']

Server time:    Pon, 15 Gru 2014 21:57:49 +0100

---

Nie bardzo wiem jak sobie z tym poradzić ?

**Comment by tomek-livenup** [comment]
Twój Fork na githubie jest trochę nieaktualny, także trudno ocenić co masz w kodzie i czy jest on aktualny względem https://github.com/dekoza/kurs_django/.

**Comment by ADDJAR** [comment]
kurs prowadze sobie na bitbucket, jest to ~0:28 min filmu sp. 4
https://bitbucket.org/addjar/kurs_django/src/7a80e5d6993a986049dcdb2a830081959c5ae6e0/?at=spotkanie_4

**Comment by ADDJAR** [comment]
doszedłem chyba sam do rozwiązania, po wyeksportowaniu modeli do bazy danych:

./manage.py makemigrations
Migrations for 'contact':
  0001_initial.py:
    - Create model Message

./manage.py migrate
Operations to perform:
  Apply all migrations: contenttypes, shelf, sessions, admin, auth, contact
Running migrations:
  Applying contact.0001_initial... OK

teraz mi wszystko działa
