### ISSUE TITLE
spotkanie 02 - Model

### ISSUE THREAD

**Issue by Strtg** [dekoza/kurs_django#9]
Ta baza danych Django z modelami, to używa MySQL, jakiegoś innego SQL, czy to jest jakiś format Django?

**Comment by dekoza** [comment]
Django używa tzw. Object Relational Mapper (ORM) do definiowania struktury bazy danych. ORM to swego rodzaju "opakowanie", dzięki któremu obsługa bazy danych jest jednolita niezależnie od wybranego silnika. W konfiguracji ustala się konkretny silnik bazy danych. Można użyć np. MySQL, PostgreSQL, SQLite, Oracle.
